#define G_LOG_USE_STRUCTURED
#include <glib.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include <errno.h>
#include "selevator.h"
#include "elevator.h"
#include "dispatch.h"